;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/11/6 22:57:17

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1012	1012	; 信息系统管理平台 1.0 - 主界面.htm
#define IDH_1008	1008	; 系统目标 1.1 - 系统目标.htm
#define IDH_1010	1010	; 系统分类 1.2 - 系统分类.htm
#define IDH_1015	1015	; 系统功能菜单 2.0 - 系统功能菜单.htm
#define IDH_1016	1016	; 第一部分 2.2 - 第一部分.htm
#define IDH_1017	1017	; 第二部分 2.2 - 第二部分.htm
#define IDH_1018	1018	; 第三部分 2.3 - 第三部分.htm
