;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2015/11/6 22:57:17

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1012=1.0 - 主界面.htm	; 信息系统管理平台
IDH_1008=1.1 - 系统目标.htm	; 系统目标
IDH_1010=1.2 - 系统分类.htm	; 系统分类
IDH_1015=2.0 - 系统功能菜单.htm	; 系统功能菜单
IDH_1016=2.2 - 第一部分.htm	; 第一部分
IDH_1017=2.2 - 第二部分.htm	; 第二部分
IDH_1018=2.3 - 第三部分.htm	; 第三部分
